In [1]:
# Importando as bibliotecas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Lendo e analisando os dados

In [ ]:
casas_df = pd.read_csv("housing.csv")
display(casas_df.head(30))
casas_df.info()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY
11,-122.26,37.85,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0,NEAR BAY
12,-122.26,37.85,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0,NEAR BAY
13,-122.26,37.84,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0,NEAR BAY
14,-122.26,37.85,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0,NEAR BAY
15,-122.26,37.85,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0,NEAR BAY
16,-122.27,37.85,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0,NEAR BAY
17,-122.27,37.85,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0,NEAR BAY
18,-122.26,37.84,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0,NEAR BAY
19,-122.27,37.84,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0,NEAR BAY
20,-122.27,37.85,40.0,751.0,184.0,409.0,166.0,1.3578,147500.0,NEAR BAY
21,-122.27,37.85,42.0,1639.0,367.0,929.0,366.0,1.7135,159800.0,NEAR BAY
22,-122.27,37.84,52.0,2436.0,541.0,1015.0,478.0,1.7250,113900.0,NEAR BAY
23,-122.27,37.84,52.0,1688.0,337.0,853.0,325.0,2.1806,99700.0,NEAR BAY
24,-122.27,37.84,52.0,2224.0,437.0,1006.0,422.0,2.6000,132600.0,NEAR BAY
25,-122.28,37.85,41.0,535.0,123.0,317.0,119.0,2.4038,107500.0,NEAR BAY
26,-122.28,37.85,49.0,1130.0,244.0,607.0,239.0,2.4597,93800.0,NEAR BAY
27,-122.28,37.85,52.0,1898.0,421.0,1102.0,397.0,1.8080,105500.0,NEAR BAY
28,-122.28,37.84,50.0,2082.0,492.0,1131.0,473.0,1.6424,108900.0,NEAR BAY
29,-122.28,37.84,52.0,729.0,160.0,395.0,155.0,1.6875,132000.0,NEAR BAY

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

TRATANDO OS DADOS PARA ALIMENTAR A IA

In [62]:
# CRIANDO CATEGORIAS

# Criando coluna "Pessoas por casa"
casas_df["person per house"] = (casas_df["population"] / casas_df["households"]).round(3)
# Tratando alguns erros dessa coluna
casas_df.loc[casas_df["person per house"] > 14] = casas_df["person per house"].mean()

# Criando a coluna "Quartos por casa"
casas_df["bedrooms per house"] = (casas_df["total_bedrooms"] / casas_df["households"]).round(3)
# Tratando alguns problemas
casas_df = casas_df[casas_df["bedrooms per house"] <= 10]

# Criando a coluna "Cômodos por casa"
casas_df["rooms per house"] = (casas_df["total_rooms"] / casas_df["households"]).round(3)

# Tratado um erro da coluna "ocean_proximity"
casas_df = casas_df[casas_df["ocean_proximity"].isin(["<1H OCEAN", "INLAND", "ISLAND", "NEAR BAY", "NEAR OCEAN"])]

In [63]:
# Criando os grupos sociais para estretificar(dividido em classe baixa, classe média e classe alta)

# Organizando por ordem 
casas_organizadas_por_renda = casas_df["median_income"].sort_values().reset_index(drop=True)

# Definindo o índice do ultimo participante da classe baixa e media
renda_base = np.min(casas_df["median_income"])
um_porcento_da_renda = (np.max(casas_df["median_income"]) - np.min(casas_df["median_income"])) / 100

classe_baixa_limite = renda_base + 28 * um_porcento_da_renda # 4.559956
classe_media_limite = renda_base + 81 * um_porcento_da_renda # 12.245061999999999

indice_ultima_casa_classe_baixa = np.argmax(casas_organizadas_por_renda >= classe_baixa_limite).astype(int) + 1
indice_ultima_casa_classe_media = np.argmax(casas_organizadas_por_renda >= classe_media_limite).astype(int) + 1

casas_df["class"] = pd.cut(
    casas_df["median_income"],
    bins = [
        0,
        casas_organizadas_por_renda[indice_ultima_casa_classe_baixa],
        casas_organizadas_por_renda[indice_ultima_casa_classe_media],
        np.inf
        ],
    labels = ["Lower class", "Middle class", "Upper class"]
)

# Quando for separar os dados para treino e teste, estratificar por classe social

Observando as correlações

In [71]:
display(casas_df[["longitude",
          "latitude",
          "housing_median_age", 
          "total_rooms", 
          "total_bedrooms", 
          "population", 
          "households", 
          "median_income", 
          "median_house_value", 
          "person per house", 
          "bedrooms per house", 
          "rooms per person", 
          "rooms per house"]
          ].corr().round(3)
)

valor_das_casas_de_acordo_com_a_proximidade_do_oceano = casas_df.groupby("ocean_proximity")["median_house_value"].mean().round(2).reset_index()
valor_das_casas_de_acordo_com_a_proximidade_do_oceano = valor_das_casas_de_acordo_com_a_proximidade_do_oceano.sort_values("median_house_value", ascending=False)
display(valor_das_casas_de_acordo_com_a_proximidade_do_oceano)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,person per house,bedrooms per house,rooms per person,rooms per house
longitude,1.000,-0.925,-0.109,0.045,0.069,0.101,0.057,-0.015,-0.045,0.157,0.020,-0.036,-0.036
latitude,-0.925,1.000,0.012,-0.036,-0.067,-0.109,-0.071,-0.080,-0.145,-0.150,0.079,0.120,0.120
housing_median_age,-0.109,0.012,1.000,-0.361,-0.321,-0.298,-0.303,-0.119,0.106,-0.004,-0.110,-0.196,-0.196
total_rooms,0.045,-0.036,-0.361,1.000,0.930,0.862,0.919,0.198,0.133,-0.109,0.048,0.178,0.178
total_bedrooms,0.069,-0.067,-0.321,0.930,1.000,0.883,0.980,-0.008,0.050,-0.144,0.071,0.004,0.004
population,0.101,-0.109,-0.298,0.862,0.883,1.000,0.912,0.004,-0.025,0.178,-0.075,-0.076,-0.076
households,0.057,-0.071,-0.303,0.919,0.980,0.912,1.000,0.013,0.065,-0.126,-0.057,-0.086,-0.086
median_income,-0.015,-0.080,-0.119,0.198,-0.008,0.004,0.013,1.000,0.689,-0.062,-0.087,0.432,0.432
median_house_value,-0.045,-0.145,0.106,0.133,0.050,-0.025,0.065,0.689,1.000,-0.250,-0.073,0.193,0.193
person per house,0.157,-0.150,-0.004,-0.109,-0.144,0.178,-0.126,-0.062,-0.250,1.000,-0.079,-0.052,-0.052
bedrooms per house,0.020,0.079,-0.110,0.048,0.071,-0.075,-0.057,-0.087,-0.073,-0.079,1.000,0.735,0.735
rooms per person,-0.036,0.120,-0.196,0.178,0.004,-0.076,-0.086,0.432,0.193,-0.052,0.735,1.000,1.000
rooms per house,-0.036,0.120,-0.196,0.178,0.004,-0.076,-0.086,0.432,0.193,-0.052,0.735,1.000,1.000

  ocean_proximity  median_house_value
2          ISLAND           380440.00
3        NEAR BAY           259294.40
4      NEAR OCEAN           249193.98
0       <1H OCEAN           240263.71
1          INLAND           124720.90

# Observano as Correlações:

Muitos dados não estão correlacionados com os preços das casas(o que é ruim)

Um dos principais features relacionados ao valor da casa é a media da renda, Pessoas que ganham mais tendem a viverem
em casas mais caras

observe a ordem de proximidade com o oceano:
 
 1 - ISLAND
 
 2 - NEAR OCEAN
 
 3 - NEAR BAY	

 4 - <1H OCEAN	

 5 - INLAND	

Oberva-se que o preço das casas tende a aumentar de acordo com a proximidade do Oceano